# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'assignservodialog.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_AssignServoDialog(object):
    def setupUi(self, AssignServoDialog):
        AssignServoDialog.setObjectName("AssignServoDialog")
        AssignServoDialog.resize(473, 246)
        self.verticalLayout = QtWidgets.QVBoxLayout(AssignServoDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Layout_settings = QtWidgets.QGridLayout()
        self.Layout_settings.setObjectName("Layout_settings")
        self.label_descr = QtWidgets.QLabel(AssignServoDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_descr.sizePolicy().hasHeightForWidth())
        self.label_descr.setSizePolicy(sizePolicy)
        self.label_descr.setAlignment(QtCore.Qt.AlignCenter)
        self.label_descr.setObjectName("label_descr")
        self.Layout_settings.addWidget(self.label_descr, 0, 0, 1, 2)
        self.groupBox_hips = QtWidgets.QGroupBox(AssignServoDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_hips.sizePolicy().hasHeightForWidth())
        self.groupBox_hips.setSizePolicy(sizePolicy)
        self.groupBox_hips.setObjectName("groupBox_hips")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_hips)
        self.gridLayout.setObjectName("gridLayout")
        self.label_hFL = QtWidgets.QLabel(self.groupBox_hips)
        self.label_hFL.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_hFL.setObjectName("label_hFL")
        self.gridLayout.addWidget(self.label_hFL, 0, 0, 1, 1)
        self.combo_hfLeft = QtWidgets.QComboBox(self.groupBox_hips)
        self.combo_hfLeft.setObjectName("combo_hfLeft")
        self.combo_hfLeft.addItem("")
        self.combo_hfLeft.addItem("")
        self.combo_hfLeft.addItem("")
        self.combo_hfLeft.addItem("")
        self.combo_hfLeft.addItem("")
        self.combo_hfLeft.addItem("")
        self.combo_hfLeft.addItem("")
        self.combo_hfLeft.addItem("")
        self.combo_hfLeft.addItem("")
        self.combo_hfLeft.addItem("")
        self.combo_hfLeft.addItem("")
        self.combo_hfLeft.addItem("")
        self.combo_hfLeft.addItem("")
        self.combo_hfLeft.addItem("")
        self.combo_hfLeft.addItem("")
        self.combo_hfLeft.addItem("")
        self.gridLayout.addWidget(self.combo_hfLeft, 0, 1, 1, 1)
        self.label_hFR = QtWidgets.QLabel(self.groupBox_hips)
        self.label_hFR.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_hFR.setObjectName("label_hFR")
        self.gridLayout.addWidget(self.label_hFR, 1, 0, 1, 1)
        self.combo_hfRight = QtWidgets.QComboBox(self.groupBox_hips)
        self.combo_hfRight.setObjectName("combo_hfRight")
        self.combo_hfRight.addItem("")
        self.combo_hfRight.addItem("")
        self.combo_hfRight.addItem("")
        self.combo_hfRight.addItem("")
        self.combo_hfRight.addItem("")
        self.combo_hfRight.addItem("")
        self.combo_hfRight.addItem("")
        self.combo_hfRight.addItem("")
        self.combo_hfRight.addItem("")
        self.combo_hfRight.addItem("")
        self.combo_hfRight.addItem("")
        self.combo_hfRight.addItem("")
        self.combo_hfRight.addItem("")
        self.combo_hfRight.addItem("")
        self.combo_hfRight.addItem("")
        self.combo_hfRight.addItem("")
        self.gridLayout.addWidget(self.combo_hfRight, 1, 1, 1, 1)
        self.label_hRL = QtWidgets.QLabel(self.groupBox_hips)
        self.label_hRL.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_hRL.setObjectName("label_hRL")
        self.gridLayout.addWidget(self.label_hRL, 2, 0, 1, 1)
        self.combo_hrLeft = QtWidgets.QComboBox(self.groupBox_hips)
        self.combo_hrLeft.setObjectName("combo_hrLeft")
        self.combo_hrLeft.addItem("")
        self.combo_hrLeft.addItem("")
        self.combo_hrLeft.addItem("")
        self.combo_hrLeft.addItem("")
        self.combo_hrLeft.addItem("")
        self.combo_hrLeft.addItem("")
        self.combo_hrLeft.addItem("")
        self.combo_hrLeft.addItem("")
        self.combo_hrLeft.addItem("")
        self.combo_hrLeft.addItem("")
        self.combo_hrLeft.addItem("")
        self.combo_hrLeft.addItem("")
        self.combo_hrLeft.addItem("")
        self.combo_hrLeft.addItem("")
        self.combo_hrLeft.addItem("")
        self.combo_hrLeft.addItem("")
        self.gridLayout.addWidget(self.combo_hrLeft, 2, 1, 1, 1)
        self.label_hRR = QtWidgets.QLabel(self.groupBox_hips)
        self.label_hRR.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_hRR.setObjectName("label_hRR")
        self.gridLayout.addWidget(self.label_hRR, 3, 0, 1, 1)
        self.combo_hrRight = QtWidgets.QComboBox(self.groupBox_hips)
        self.combo_hrRight.setObjectName("combo_hrRight")
        self.combo_hrRight.addItem("")
        self.combo_hrRight.addItem("")
        self.combo_hrRight.addItem("")
        self.combo_hrRight.addItem("")
        self.combo_hrRight.addItem("")
        self.combo_hrRight.addItem("")
        self.combo_hrRight.addItem("")
        self.combo_hrRight.addItem("")
        self.combo_hrRight.addItem("")
        self.combo_hrRight.addItem("")
        self.combo_hrRight.addItem("")
        self.combo_hrRight.addItem("")
        self.combo_hrRight.addItem("")
        self.combo_hrRight.addItem("")
        self.combo_hrRight.addItem("")
        self.combo_hrRight.addItem("")
        self.gridLayout.addWidget(self.combo_hrRight, 3, 1, 1, 1)
        self.Layout_settings.addWidget(self.groupBox_hips, 1, 0, 1, 1)
        self.groupBox_knees = QtWidgets.QGroupBox(AssignServoDialog)
        self.groupBox_knees.setObjectName("groupBox_knees")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_knees)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_kFL = QtWidgets.QLabel(self.groupBox_knees)
        self.label_kFL.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_kFL.setObjectName("label_kFL")
        self.gridLayout_2.addWidget(self.label_kFL, 0, 0, 1, 1)
        self.combo_kFLeft = QtWidgets.QComboBox(self.groupBox_knees)
        self.combo_kFLeft.setObjectName("combo_kFLeft")
        self.combo_kFLeft.addItem("")
        self.combo_kFLeft.addItem("")
        self.combo_kFLeft.addItem("")
        self.combo_kFLeft.addItem("")
        self.combo_kFLeft.addItem("")
        self.combo_kFLeft.addItem("")
        self.combo_kFLeft.addItem("")
        self.combo_kFLeft.addItem("")
        self.combo_kFLeft.addItem("")
        self.combo_kFLeft.addItem("")
        self.combo_kFLeft.addItem("")
        self.combo_kFLeft.addItem("")
        self.combo_kFLeft.addItem("")
        self.combo_kFLeft.addItem("")
        self.combo_kFLeft.addItem("")
        self.combo_kFLeft.addItem("")
        self.gridLayout_2.addWidget(self.combo_kFLeft, 0, 1, 1, 1)
        self.label_kFR = QtWidgets.QLabel(self.groupBox_knees)
        self.label_kFR.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_kFR.setObjectName("label_kFR")
        self.gridLayout_2.addWidget(self.label_kFR, 1, 0, 1, 1)
        self.combo_kFRight = QtWidgets.QComboBox(self.groupBox_knees)
        self.combo_kFRight.setObjectName("combo_kFRight")
        self.combo_kFRight.addItem("")
        self.combo_kFRight.addItem("")
        self.combo_kFRight.addItem("")
        self.combo_kFRight.addItem("")
        self.combo_kFRight.addItem("")
        self.combo_kFRight.addItem("")
        self.combo_kFRight.addItem("")
        self.combo_kFRight.addItem("")
        self.combo_kFRight.addItem("")
        self.combo_kFRight.addItem("")
        self.combo_kFRight.addItem("")
        self.combo_kFRight.addItem("")
        self.combo_kFRight.addItem("")
        self.combo_kFRight.addItem("")
        self.combo_kFRight.addItem("")
        self.combo_kFRight.addItem("")
        self.gridLayout_2.addWidget(self.combo_kFRight, 1, 1, 1, 1)
        self.label_kRL = QtWidgets.QLabel(self.groupBox_knees)
        self.label_kRL.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_kRL.setObjectName("label_kRL")
        self.gridLayout_2.addWidget(self.label_kRL, 2, 0, 1, 1)
        self.combo_kRLeft = QtWidgets.QComboBox(self.groupBox_knees)
        self.combo_kRLeft.setObjectName("combo_kRLeft")
        self.combo_kRLeft.addItem("")
        self.combo_kRLeft.addItem("")
        self.combo_kRLeft.addItem("")
        self.combo_kRLeft.addItem("")
        self.combo_kRLeft.addItem("")
        self.combo_kRLeft.addItem("")
        self.combo_kRLeft.addItem("")
        self.combo_kRLeft.addItem("")
        self.combo_kRLeft.addItem("")
        self.combo_kRLeft.addItem("")
        self.combo_kRLeft.addItem("")
        self.combo_kRLeft.addItem("")
        self.combo_kRLeft.addItem("")
        self.combo_kRLeft.addItem("")
        self.combo_kRLeft.addItem("")
        self.combo_kRLeft.addItem("")
        self.gridLayout_2.addWidget(self.combo_kRLeft, 2, 1, 1, 1)
        self.label_kRR = QtWidgets.QLabel(self.groupBox_knees)
        self.label_kRR.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_kRR.setObjectName("label_kRR")
        self.gridLayout_2.addWidget(self.label_kRR, 3, 0, 1, 1)
        self.combo_kRRight = QtWidgets.QComboBox(self.groupBox_knees)
        self.combo_kRRight.setObjectName("combo_kRRight")
        self.combo_kRRight.addItem("")
        self.combo_kRRight.addItem("")
        self.combo_kRRight.addItem("")
        self.combo_kRRight.addItem("")
        self.combo_kRRight.addItem("")
        self.combo_kRRight.addItem("")
        self.combo_kRRight.addItem("")
        self.combo_kRRight.addItem("")
        self.combo_kRRight.addItem("")
        self.combo_kRRight.addItem("")
        self.combo_kRRight.addItem("")
        self.combo_kRRight.addItem("")
        self.combo_kRRight.addItem("")
        self.combo_kRRight.addItem("")
        self.combo_kRRight.addItem("")
        self.combo_kRRight.addItem("")
        self.gridLayout_2.addWidget(self.combo_kRRight, 3, 1, 1, 1)
        self.Layout_settings.addWidget(self.groupBox_knees, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.Layout_settings)
        self.buttonBox = QtWidgets.QDialogButtonBox(AssignServoDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok|QtWidgets.QDialogButtonBox.RestoreDefaults)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(AssignServoDialog)
        self.buttonBox.accepted.connect(AssignServoDialog.accept)
        self.buttonBox.rejected.connect(AssignServoDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(AssignServoDialog)

    def retranslateUi(self, AssignServoDialog):
        _translate = QtCore.QCoreApplication.translate
        AssignServoDialog.setWindowTitle(_translate("AssignServoDialog", "Dialog"))
        self.label_descr.setText(_translate("AssignServoDialog", "VR408: ALLBOT four-legged robot with two joints per leg"))
        self.groupBox_hips.setTitle(_translate("AssignServoDialog", "Hip Joints"))
        self.label_hFL.setText(_translate("AssignServoDialog", "hipFrontLeft"))
        self.combo_hfLeft.setItemText(0, _translate("AssignServoDialog", "Channel 0"))
        self.combo_hfLeft.setItemText(1, _translate("AssignServoDialog", "Channel 1"))
        self.combo_hfLeft.setItemText(2, _translate("AssignServoDialog", "Channel 2"))
        self.combo_hfLeft.setItemText(3, _translate("AssignServoDialog", "Channel 3"))
        self.combo_hfLeft.setItemText(4, _translate("AssignServoDialog", "Channel 4"))
        self.combo_hfLeft.setItemText(5, _translate("AssignServoDialog", "Channel 5"))
        self.combo_hfLeft.setItemText(6, _translate("AssignServoDialog", "Channel 6"))
        self.combo_hfLeft.setItemText(7, _translate("AssignServoDialog", "Channel 7"))
        self.combo_hfLeft.setItemText(8, _translate("AssignServoDialog", "Channel 8"))
        self.combo_hfLeft.setItemText(9, _translate("AssignServoDialog", "Channel 9"))
        self.combo_hfLeft.setItemText(10, _translate("AssignServoDialog", "Channel 10"))
        self.combo_hfLeft.setItemText(11, _translate("AssignServoDialog", "Channel 11"))
        self.combo_hfLeft.setItemText(12, _translate("AssignServoDialog", "Channel 12"))
        self.combo_hfLeft.setItemText(13, _translate("AssignServoDialog", "Channel 13"))
        self.combo_hfLeft.setItemText(14, _translate("AssignServoDialog", "Channel 14"))
        self.combo_hfLeft.setItemText(15, _translate("AssignServoDialog", "Channel 15"))
        self.label_hFR.setText(_translate("AssignServoDialog", "hipFrontRight"))
        self.combo_hfRight.setItemText(0, _translate("AssignServoDialog", "Channel 0"))
        self.combo_hfRight.setItemText(1, _translate("AssignServoDialog", "Channel 1"))
        self.combo_hfRight.setItemText(2, _translate("AssignServoDialog", "Channel 2"))
        self.combo_hfRight.setItemText(3, _translate("AssignServoDialog", "Channel 3"))
        self.combo_hfRight.setItemText(4, _translate("AssignServoDialog", "Channel 4"))
        self.combo_hfRight.setItemText(5, _translate("AssignServoDialog", "Channel 5"))
        self.combo_hfRight.setItemText(6, _translate("AssignServoDialog", "Channel 6"))
        self.combo_hfRight.setItemText(7, _translate("AssignServoDialog", "Channel 7"))
        self.combo_hfRight.setItemText(8, _translate("AssignServoDialog", "Channel 8"))
        self.combo_hfRight.setItemText(9, _translate("AssignServoDialog", "Channel 9"))
        self.combo_hfRight.setItemText(10, _translate("AssignServoDialog", "Channel 10"))
        self.combo_hfRight.setItemText(11, _translate("AssignServoDialog", "Channel 11"))
        self.combo_hfRight.setItemText(12, _translate("AssignServoDialog", "Channel 12"))
        self.combo_hfRight.setItemText(13, _translate("AssignServoDialog", "Channel 13"))
        self.combo_hfRight.setItemText(14, _translate("AssignServoDialog", "Channel 14"))
        self.combo_hfRight.setItemText(15, _translate("AssignServoDialog", "Channel 15"))
        self.label_hRL.setText(_translate("AssignServoDialog", "hipRearLeft"))
        self.combo_hrLeft.setItemText(0, _translate("AssignServoDialog", "Channel 0"))
        self.combo_hrLeft.setItemText(1, _translate("AssignServoDialog", "Channel 1"))
        self.combo_hrLeft.setItemText(2, _translate("AssignServoDialog", "Channel 2"))
        self.combo_hrLeft.setItemText(3, _translate("AssignServoDialog", "Channel 3"))
        self.combo_hrLeft.setItemText(4, _translate("AssignServoDialog", "Channel 4"))
        self.combo_hrLeft.setItemText(5, _translate("AssignServoDialog", "Channel 5"))
        self.combo_hrLeft.setItemText(6, _translate("AssignServoDialog", "Channel 6"))
        self.combo_hrLeft.setItemText(7, _translate("AssignServoDialog", "Channel 7"))
        self.combo_hrLeft.setItemText(8, _translate("AssignServoDialog", "Channel 8"))
        self.combo_hrLeft.setItemText(9, _translate("AssignServoDialog", "Channel 9"))
        self.combo_hrLeft.setItemText(10, _translate("AssignServoDialog", "Channel 10"))
        self.combo_hrLeft.setItemText(11, _translate("AssignServoDialog", "Channel 11"))
        self.combo_hrLeft.setItemText(12, _translate("AssignServoDialog", "Channel 12"))
        self.combo_hrLeft.setItemText(13, _translate("AssignServoDialog", "Channel 13"))
        self.combo_hrLeft.setItemText(14, _translate("AssignServoDialog", "Channel 14"))
        self.combo_hrLeft.setItemText(15, _translate("AssignServoDialog", "Channel 15"))
        self.label_hRR.setText(_translate("AssignServoDialog", "hipRearRight"))
        self.combo_hrRight.setItemText(0, _translate("AssignServoDialog", "Channel 0"))
        self.combo_hrRight.setItemText(1, _translate("AssignServoDialog", "Channel 1"))
        self.combo_hrRight.setItemText(2, _translate("AssignServoDialog", "Channel 2"))
        self.combo_hrRight.setItemText(3, _translate("AssignServoDialog", "Channel 3"))
        self.combo_hrRight.setItemText(4, _translate("AssignServoDialog", "Channel 4"))
        self.combo_hrRight.setItemText(5, _translate("AssignServoDialog", "Channel 5"))
        self.combo_hrRight.setItemText(6, _translate("AssignServoDialog", "Channel 6"))
        self.combo_hrRight.setItemText(7, _translate("AssignServoDialog", "Channel 7"))
        self.combo_hrRight.setItemText(8, _translate("AssignServoDialog", "Channel 8"))
        self.combo_hrRight.setItemText(9, _translate("AssignServoDialog", "Channel 9"))
        self.combo_hrRight.setItemText(10, _translate("AssignServoDialog", "Channel 10"))
        self.combo_hrRight.setItemText(11, _translate("AssignServoDialog", "Channel 11"))
        self.combo_hrRight.setItemText(12, _translate("AssignServoDialog", "Channel 12"))
        self.combo_hrRight.setItemText(13, _translate("AssignServoDialog", "Channel 13"))
        self.combo_hrRight.setItemText(14, _translate("AssignServoDialog", "Channel 14"))
        self.combo_hrRight.setItemText(15, _translate("AssignServoDialog", "Channel 15"))
        self.groupBox_knees.setTitle(_translate("AssignServoDialog", "Knee Joints"))
        self.label_kFL.setText(_translate("AssignServoDialog", "kneeFrontLeft"))
        self.combo_kFLeft.setItemText(0, _translate("AssignServoDialog", "Channel 0"))
        self.combo_kFLeft.setItemText(1, _translate("AssignServoDialog", "Channel 1"))
        self.combo_kFLeft.setItemText(2, _translate("AssignServoDialog", "Channel 2"))
        self.combo_kFLeft.setItemText(3, _translate("AssignServoDialog", "Channel 3"))
        self.combo_kFLeft.setItemText(4, _translate("AssignServoDialog", "Channel 4"))
        self.combo_kFLeft.setItemText(5, _translate("AssignServoDialog", "Channel 5"))
        self.combo_kFLeft.setItemText(6, _translate("AssignServoDialog", "Channel 6"))
        self.combo_kFLeft.setItemText(7, _translate("AssignServoDialog", "Channel 7"))
        self.combo_kFLeft.setItemText(8, _translate("AssignServoDialog", "Channel 8"))
        self.combo_kFLeft.setItemText(9, _translate("AssignServoDialog", "Channel 9"))
        self.combo_kFLeft.setItemText(10, _translate("AssignServoDialog", "Channel 10"))
        self.combo_kFLeft.setItemText(11, _translate("AssignServoDialog", "Channel 11"))
        self.combo_kFLeft.setItemText(12, _translate("AssignServoDialog", "Channel 12"))
        self.combo_kFLeft.setItemText(13, _translate("AssignServoDialog", "Channel 13"))
        self.combo_kFLeft.setItemText(14, _translate("AssignServoDialog", "Channel 14"))
        self.combo_kFLeft.setItemText(15, _translate("AssignServoDialog", "Channel 15"))
        self.label_kFR.setText(_translate("AssignServoDialog", "kneeFrontRight"))
        self.combo_kFRight.setItemText(0, _translate("AssignServoDialog", "Channel 0"))
        self.combo_kFRight.setItemText(1, _translate("AssignServoDialog", "Channel 1"))
        self.combo_kFRight.setItemText(2, _translate("AssignServoDialog", "Channel 2"))
        self.combo_kFRight.setItemText(3, _translate("AssignServoDialog", "Channel 3"))
        self.combo_kFRight.setItemText(4, _translate("AssignServoDialog", "Channel 4"))
        self.combo_kFRight.setItemText(5, _translate("AssignServoDialog", "Channel 5"))
        self.combo_kFRight.setItemText(6, _translate("AssignServoDialog", "Channel 6"))
        self.combo_kFRight.setItemText(7, _translate("AssignServoDialog", "Channel 7"))
        self.combo_kFRight.setItemText(8, _translate("AssignServoDialog", "Channel 8"))
        self.combo_kFRight.setItemText(9, _translate("AssignServoDialog", "Channel 9"))
        self.combo_kFRight.setItemText(10, _translate("AssignServoDialog", "Channel 10"))
        self.combo_kFRight.setItemText(11, _translate("AssignServoDialog", "Channel 11"))
        self.combo_kFRight.setItemText(12, _translate("AssignServoDialog", "Channel 12"))
        self.combo_kFRight.setItemText(13, _translate("AssignServoDialog", "Channel 13"))
        self.combo_kFRight.setItemText(14, _translate("AssignServoDialog", "Channel 14"))
        self.combo_kFRight.setItemText(15, _translate("AssignServoDialog", "Channel 15"))
        self.label_kRL.setText(_translate("AssignServoDialog", "kneeRearLeft"))
        self.combo_kRLeft.setItemText(0, _translate("AssignServoDialog", "Channel 0"))
        self.combo_kRLeft.setItemText(1, _translate("AssignServoDialog", "Channel 1"))
        self.combo_kRLeft.setItemText(2, _translate("AssignServoDialog", "Channel 2"))
        self.combo_kRLeft.setItemText(3, _translate("AssignServoDialog", "Channel 3"))
        self.combo_kRLeft.setItemText(4, _translate("AssignServoDialog", "Channel 4"))
        self.combo_kRLeft.setItemText(5, _translate("AssignServoDialog", "Channel 5"))
        self.combo_kRLeft.setItemText(6, _translate("AssignServoDialog", "Channel 6"))
        self.combo_kRLeft.setItemText(7, _translate("AssignServoDialog", "Channel 7"))
        self.combo_kRLeft.setItemText(8, _translate("AssignServoDialog", "Channel 8"))
        self.combo_kRLeft.setItemText(9, _translate("AssignServoDialog", "Channel 9"))
        self.combo_kRLeft.setItemText(10, _translate("AssignServoDialog", "Channel 10"))
        self.combo_kRLeft.setItemText(11, _translate("AssignServoDialog", "Channel 11"))
        self.combo_kRLeft.setItemText(12, _translate("AssignServoDialog", "Channel 12"))
        self.combo_kRLeft.setItemText(13, _translate("AssignServoDialog", "Channel 13"))
        self.combo_kRLeft.setItemText(14, _translate("AssignServoDialog", "Channel 14"))
        self.combo_kRLeft.setItemText(15, _translate("AssignServoDialog", "Channel 15"))
        self.label_kRR.setText(_translate("AssignServoDialog", "kneeRearRight"))
        self.combo_kRRight.setItemText(0, _translate("AssignServoDialog", "Channel 0"))
        self.combo_kRRight.setItemText(1, _translate("AssignServoDialog", "Channel 1"))
        self.combo_kRRight.setItemText(2, _translate("AssignServoDialog", "Channel 2"))
        self.combo_kRRight.setItemText(3, _translate("AssignServoDialog", "Channel 3"))
        self.combo_kRRight.setItemText(4, _translate("AssignServoDialog", "Channel 4"))
        self.combo_kRRight.setItemText(5, _translate("AssignServoDialog", "Channel 5"))
        self.combo_kRRight.setItemText(6, _translate("AssignServoDialog", "Channel 6"))
        self.combo_kRRight.setItemText(7, _translate("AssignServoDialog", "Channel 7"))
        self.combo_kRRight.setItemText(8, _translate("AssignServoDialog", "Channel 8"))
        self.combo_kRRight.setItemText(9, _translate("AssignServoDialog", "Channel 9"))
        self.combo_kRRight.setItemText(10, _translate("AssignServoDialog", "Channel 10"))
        self.combo_kRRight.setItemText(11, _translate("AssignServoDialog", "Channel 11"))
        self.combo_kRRight.setItemText(12, _translate("AssignServoDialog", "Channel 12"))
        self.combo_kRRight.setItemText(13, _translate("AssignServoDialog", "Channel 13"))
        self.combo_kRRight.setItemText(14, _translate("AssignServoDialog", "Channel 14"))
        self.combo_kRRight.setItemText(15, _translate("AssignServoDialog", "Channel 15"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AssignServoDialog = QtWidgets.QDialog()
    ui = Ui_AssignServoDialog()
    ui.setupUi(AssignServoDialog)
    AssignServoDialog.show()
    sys.exit(app.exec_())

