# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialogservoconfig.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DialogServoConfig(object):
    def setupUi(self, DialogServoConfig):
        DialogServoConfig.setObjectName("DialogServoConfig")
        DialogServoConfig.resize(264, 290)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(DialogServoConfig)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox_hware = QtWidgets.QGroupBox(DialogServoConfig)
        self.groupBox_hware.setObjectName("groupBox_hware")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_hware)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Layout_iicBus = QtWidgets.QHBoxLayout()
        self.Layout_iicBus.setObjectName("Layout_iicBus")
        self.label_iicBus = QtWidgets.QLabel(self.groupBox_hware)
        self.label_iicBus.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_iicBus.setObjectName("label_iicBus")
        self.Layout_iicBus.addWidget(self.label_iicBus)
        self.combo_selBus = QtWidgets.QComboBox(self.groupBox_hware)
        self.combo_selBus.setObjectName("combo_selBus")
        self.combo_selBus.addItem("")
        self.combo_selBus.addItem("")
        self.Layout_iicBus.addWidget(self.combo_selBus)
        self.label_defaultBus = QtWidgets.QLabel(self.groupBox_hware)
        self.label_defaultBus.setObjectName("label_defaultBus")
        self.Layout_iicBus.addWidget(self.label_defaultBus)
        self.verticalLayout.addLayout(self.Layout_iicBus)
        self.Layout_iicAddress = QtWidgets.QHBoxLayout()
        self.Layout_iicAddress.setObjectName("Layout_iicAddress")
        self.label_iicAddress = QtWidgets.QLabel(self.groupBox_hware)
        self.label_iicAddress.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_iicAddress.setObjectName("label_iicAddress")
        self.Layout_iicAddress.addWidget(self.label_iicAddress)
        self.lineEdit_Address = QtWidgets.QLineEdit(self.groupBox_hware)
        self.lineEdit_Address.setObjectName("lineEdit_Address")
        self.Layout_iicAddress.addWidget(self.lineEdit_Address)
        self.label_defaultAddress = QtWidgets.QLabel(self.groupBox_hware)
        self.label_defaultAddress.setObjectName("label_defaultAddress")
        self.Layout_iicAddress.addWidget(self.label_defaultAddress)
        self.verticalLayout.addLayout(self.Layout_iicAddress)
        self.verticalLayout_3.addWidget(self.groupBox_hware)
        self.groupBox_sware = QtWidgets.QGroupBox(DialogServoConfig)
        self.groupBox_sware.setObjectName("groupBox_sware")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_sware)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Layout_frequency = QtWidgets.QHBoxLayout()
        self.Layout_frequency.setObjectName("Layout_frequency")
        self.label_frequency = QtWidgets.QLabel(self.groupBox_sware)
        self.label_frequency.setObjectName("label_frequency")
        self.Layout_frequency.addWidget(self.label_frequency)
        self.lineEdit_fvalue = QtWidgets.QLineEdit(self.groupBox_sware)
        self.lineEdit_fvalue.setObjectName("lineEdit_fvalue")
        self.Layout_frequency.addWidget(self.lineEdit_fvalue)
        self.combo_unit = QtWidgets.QComboBox(self.groupBox_sware)
        self.combo_unit.setObjectName("combo_unit")
        self.combo_unit.addItem("")
        self.combo_unit.addItem("")
        self.combo_unit.addItem("")
        self.Layout_frequency.addWidget(self.combo_unit)
        self.verticalLayout_2.addLayout(self.Layout_frequency)
        self.Layout_minAngle = QtWidgets.QHBoxLayout()
        self.Layout_minAngle.setObjectName("Layout_minAngle")
        self.label_minAngle = QtWidgets.QLabel(self.groupBox_sware)
        self.label_minAngle.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_minAngle.setObjectName("label_minAngle")
        self.Layout_minAngle.addWidget(self.label_minAngle)
        self.lineEdit_minAngleVal = QtWidgets.QLineEdit(self.groupBox_sware)
        self.lineEdit_minAngleVal.setText("")
        self.lineEdit_minAngleVal.setObjectName("lineEdit_minAngleVal")
        self.Layout_minAngle.addWidget(self.lineEdit_minAngleVal)
        self.label_40961 = QtWidgets.QLabel(self.groupBox_sware)
        self.label_40961.setObjectName("label_40961")
        self.Layout_minAngle.addWidget(self.label_40961)
        self.verticalLayout_2.addLayout(self.Layout_minAngle)
        self.Layout_maxAngle = QtWidgets.QHBoxLayout()
        self.Layout_maxAngle.setObjectName("Layout_maxAngle")
        self.label_maxAngle = QtWidgets.QLabel(self.groupBox_sware)
        self.label_maxAngle.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_maxAngle.setObjectName("label_maxAngle")
        self.Layout_maxAngle.addWidget(self.label_maxAngle)
        self.lineEdit_maxAngleVal = QtWidgets.QLineEdit(self.groupBox_sware)
        self.lineEdit_maxAngleVal.setText("")
        self.lineEdit_maxAngleVal.setObjectName("lineEdit_maxAngleVal")
        self.Layout_maxAngle.addWidget(self.lineEdit_maxAngleVal)
        self.label_40962 = QtWidgets.QLabel(self.groupBox_sware)
        self.label_40962.setObjectName("label_40962")
        self.Layout_maxAngle.addWidget(self.label_40962)
        self.verticalLayout_2.addLayout(self.Layout_maxAngle)
        self.verticalLayout_3.addWidget(self.groupBox_sware)
        self.buttonBox = QtWidgets.QDialogButtonBox(DialogServoConfig)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_3.addWidget(self.buttonBox)

        self.retranslateUi(DialogServoConfig)
        QtCore.QMetaObject.connectSlotsByName(DialogServoConfig)

    def retranslateUi(self, DialogServoConfig):
        _translate = QtCore.QCoreApplication.translate
        DialogServoConfig.setWindowTitle(_translate("DialogServoConfig", "Dialog"))
        self.groupBox_hware.setTitle(_translate("DialogServoConfig", "Hardware Settings"))
        self.label_iicBus.setText(_translate("DialogServoConfig", "I2C Bus:"))
        self.combo_selBus.setItemText(0, _translate("DialogServoConfig", "Bus 1"))
        self.combo_selBus.setItemText(1, _translate("DialogServoConfig", "Bus 0"))
        self.label_defaultBus.setText(_translate("DialogServoConfig", "(Default Bus 1)"))
        self.label_iicAddress.setText(_translate("DialogServoConfig", "I2C Address:"))
        self.lineEdit_Address.setText(_translate("DialogServoConfig", "0x40"))
        self.label_defaultAddress.setText(_translate("DialogServoConfig", "(Default 0x40)"))
        self.groupBox_sware.setTitle(_translate("DialogServoConfig", "Software Settings"))
        self.label_frequency.setText(_translate("DialogServoConfig", "Pulse Frequency:"))
        self.combo_unit.setItemText(0, _translate("DialogServoConfig", "Hz"))
        self.combo_unit.setItemText(1, _translate("DialogServoConfig", "Period"))
        self.combo_unit.setItemText(2, _translate("DialogServoConfig", "Counts"))
        self.label_minAngle.setText(_translate("DialogServoConfig", "Minimum angle:"))
        self.label_40961.setText(_translate("DialogServoConfig", "/ 4096"))
        self.label_maxAngle.setText(_translate("DialogServoConfig", "Maximum angle:"))
        self.label_40962.setText(_translate("DialogServoConfig", "/ 4096"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DialogServoConfig = QtWidgets.QDialog()
    ui = Ui_DialogServoConfig()
    ui.setupUi(DialogServoConfig)
    DialogServoConfig.show()
    sys.exit(app.exec_())

