# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vr408mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_RosBotMainWindow(object):
    def setupUi(self, RosBotMainWindow):
        RosBotMainWindow.setObjectName("RosBotMainWindow")
        RosBotMainWindow.resize(517, 590)
        RosBotMainWindow.setMaximumSize(QtCore.QSize(1022, 16777215))
        self.centralWidget = QtWidgets.QWidget(RosBotMainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout_16.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_16.setSpacing(6)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.groupBox_diag = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_diag.setObjectName("groupBox_diag")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_diag)
        self.verticalLayout_6.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_6.setSpacing(6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.textBrowser_log = QtWidgets.QTextBrowser(self.groupBox_diag)
        self.textBrowser_log.setObjectName("textBrowser_log")
        self.verticalLayout_6.addWidget(self.textBrowser_log)
        self.gridLayout_16.addWidget(self.groupBox_diag, 3, 0, 1, 2)
        self.groupBox_battery = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_battery.setObjectName("groupBox_battery")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.groupBox_battery)
        self.gridLayout_14.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_14.setSpacing(6)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.label_pwrRPi = QtWidgets.QLabel(self.groupBox_battery)
        self.label_pwrRPi.setObjectName("label_pwrRPi")
        self.gridLayout_14.addWidget(self.label_pwrRPi, 1, 0, 1, 1)
        self.pBar_RPi = QtWidgets.QProgressBar(self.groupBox_battery)
        self.pBar_RPi.setEnabled(False)
        self.pBar_RPi.setProperty("value", 0)
        self.pBar_RPi.setObjectName("pBar_RPi")
        self.gridLayout_14.addWidget(self.pBar_RPi, 1, 1, 1, 1)
        self.label_pwrMotor = QtWidgets.QLabel(self.groupBox_battery)
        self.label_pwrMotor.setObjectName("label_pwrMotor")
        self.gridLayout_14.addWidget(self.label_pwrMotor, 0, 0, 1, 1)
        self.pBar_Motor = QtWidgets.QProgressBar(self.groupBox_battery)
        self.pBar_Motor.setEnabled(False)
        self.pBar_Motor.setProperty("value", 0)
        self.pBar_Motor.setTextVisible(True)
        self.pBar_Motor.setObjectName("pBar_Motor")
        self.gridLayout_14.addWidget(self.pBar_Motor, 0, 1, 1, 1)
        self.gridLayout_16.addWidget(self.groupBox_battery, 2, 0, 1, 1)
        self.tabs_teleop = QtWidgets.QTabWidget(self.centralWidget)
        self.tabs_teleop.setMaximumSize(QtCore.QSize(700, 16777215))
        self.tabs_teleop.setAutoFillBackground(False)
        self.tabs_teleop.setObjectName("tabs_teleop")
        self.tab_Movement = QtWidgets.QWidget()
        self.tab_Movement.setEnabled(True)
        self.tab_Movement.setObjectName("tab_Movement")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_Movement)
        self.gridLayout_4.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_4.setSpacing(6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_movement = QtWidgets.QGridLayout()
        self.gridLayout_movement.setSpacing(6)
        self.gridLayout_movement.setObjectName("gridLayout_movement")
        self.gridLayout_speed = QtWidgets.QGridLayout()
        self.gridLayout_speed.setSpacing(6)
        self.gridLayout_speed.setObjectName("gridLayout_speed")
        self.groupBox_speed = QtWidgets.QGroupBox(self.tab_Movement)
        self.groupBox_speed.setObjectName("groupBox_speed")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox_speed)
        self.horizontalLayout_5.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_min = QtWidgets.QLabel(self.groupBox_speed)
        self.label_min.setObjectName("label_min")
        self.horizontalLayout_5.addWidget(self.label_min)
        self.speedSlider = QtWidgets.QSlider(self.groupBox_speed)
        self.speedSlider.setOrientation(QtCore.Qt.Horizontal)
        self.speedSlider.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.speedSlider.setObjectName("speedSlider")
        self.horizontalLayout_5.addWidget(self.speedSlider)
        self.label_max = QtWidgets.QLabel(self.groupBox_speed)
        self.label_max.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_max.setObjectName("label_max")
        self.horizontalLayout_5.addWidget(self.label_max)
        self.gridLayout_speed.addWidget(self.groupBox_speed, 0, 0, 1, 1)
        self.gridLayout_movement.addLayout(self.gridLayout_speed, 1, 1, 1, 1)
        self.groupBox_linear = QtWidgets.QGroupBox(self.tab_Movement)
        self.groupBox_linear.setObjectName("groupBox_linear")
        self.gridLayout_direction = QtWidgets.QGridLayout(self.groupBox_linear)
        self.gridLayout_direction.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_direction.setSpacing(6)
        self.gridLayout_direction.setObjectName("gridLayout_direction")
        self.Button_backward = QtWidgets.QPushButton(self.groupBox_linear)
        self.Button_backward.setObjectName("Button_backward")
        self.gridLayout_direction.addWidget(self.Button_backward, 2, 1, 1, 1)
        self.Button_forward = QtWidgets.QPushButton(self.groupBox_linear)
        self.Button_forward.setObjectName("Button_forward")
        self.gridLayout_direction.addWidget(self.Button_forward, 0, 1, 1, 1)
        self.Button_left = QtWidgets.QPushButton(self.groupBox_linear)
        self.Button_left.setObjectName("Button_left")
        self.gridLayout_direction.addWidget(self.Button_left, 1, 2, 1, 1)
        self.Button_right = QtWidgets.QPushButton(self.groupBox_linear)
        self.Button_right.setObjectName("Button_right")
        self.gridLayout_direction.addWidget(self.Button_right, 1, 0, 1, 1)
        self.gridLayout_movement.addWidget(self.groupBox_linear, 0, 0, 2, 1)
        self.groupBox_angular = QtWidgets.QGroupBox(self.tab_Movement)
        self.groupBox_angular.setObjectName("groupBox_angular")
        self.gridLayout_rotate = QtWidgets.QGridLayout(self.groupBox_angular)
        self.gridLayout_rotate.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_rotate.setSpacing(6)
        self.gridLayout_rotate.setObjectName("gridLayout_rotate")
        self.Button_zminus = QtWidgets.QPushButton(self.groupBox_angular)
        self.Button_zminus.setObjectName("Button_zminus")
        self.gridLayout_rotate.addWidget(self.Button_zminus, 0, 0, 1, 1)
        self.Button_zplus = QtWidgets.QPushButton(self.groupBox_angular)
        self.Button_zplus.setObjectName("Button_zplus")
        self.gridLayout_rotate.addWidget(self.Button_zplus, 0, 1, 1, 1)
        self.gridLayout_movement.addWidget(self.groupBox_angular, 0, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_movement, 0, 0, 1, 1)
        self.tabs_teleop.addTab(self.tab_Movement, "")
        self.tab_gestures = QtWidgets.QWidget()
        self.tab_gestures.setObjectName("tab_gestures")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tab_gestures)
        self.gridLayout_7.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_7.setSpacing(6)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.groupBox_wave = QtWidgets.QGroupBox(self.tab_gestures)
        self.groupBox_wave.setObjectName("groupBox_wave")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_wave)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.radioB_fLeft = QtWidgets.QRadioButton(self.groupBox_wave)
        self.radioB_fLeft.setObjectName("radioB_fLeft")
        self.verticalLayout_2.addWidget(self.radioB_fLeft)
        self.radioB_fRight = QtWidgets.QRadioButton(self.groupBox_wave)
        self.radioB_fRight.setObjectName("radioB_fRight")
        self.verticalLayout_2.addWidget(self.radioB_fRight)
        self.radioB_rLeft = QtWidgets.QRadioButton(self.groupBox_wave)
        self.radioB_rLeft.setObjectName("radioB_rLeft")
        self.verticalLayout_2.addWidget(self.radioB_rLeft)
        self.radioB_rRight = QtWidgets.QRadioButton(self.groupBox_wave)
        self.radioB_rRight.setObjectName("radioB_rRight")
        self.verticalLayout_2.addWidget(self.radioB_rRight)
        self.Button_wave = QtWidgets.QPushButton(self.groupBox_wave)
        self.Button_wave.setObjectName("Button_wave")
        self.verticalLayout_2.addWidget(self.Button_wave)
        self.gridLayout_7.addWidget(self.groupBox_wave, 0, 0, 2, 1)
        self.groupBox_lean = QtWidgets.QGroupBox(self.tab_gestures)
        self.groupBox_lean.setObjectName("groupBox_lean")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_lean)
        self.verticalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.radioB_left = QtWidgets.QRadioButton(self.groupBox_lean)
        self.radioB_left.setObjectName("radioB_left")
        self.verticalLayout_3.addWidget(self.radioB_left)
        self.radioB_right = QtWidgets.QRadioButton(self.groupBox_lean)
        self.radioB_right.setObjectName("radioB_right")
        self.verticalLayout_3.addWidget(self.radioB_right)
        self.radioB_forward = QtWidgets.QRadioButton(self.groupBox_lean)
        self.radioB_forward.setObjectName("radioB_forward")
        self.verticalLayout_3.addWidget(self.radioB_forward)
        self.radioB_backward = QtWidgets.QRadioButton(self.groupBox_lean)
        self.radioB_backward.setObjectName("radioB_backward")
        self.verticalLayout_3.addWidget(self.radioB_backward)
        self.Button_lean = QtWidgets.QPushButton(self.groupBox_lean)
        self.Button_lean.setObjectName("Button_lean")
        self.verticalLayout_3.addWidget(self.Button_lean)
        self.gridLayout_7.addWidget(self.groupBox_lean, 0, 1, 2, 1)
        self.groupBox_scared = QtWidgets.QGroupBox(self.tab_gestures)
        self.groupBox_scared.setObjectName("groupBox_scared")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_scared)
        self.verticalLayout_7.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_7.setSpacing(6)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.Button_animate = QtWidgets.QPushButton(self.groupBox_scared)
        self.Button_animate.setObjectName("Button_animate")
        self.verticalLayout_7.addWidget(self.Button_animate)
        self.Layout_shakes = QtWidgets.QHBoxLayout()
        self.Layout_shakes.setSpacing(6)
        self.Layout_shakes.setObjectName("Layout_shakes")
        self.label_shakes = QtWidgets.QLabel(self.groupBox_scared)
        self.label_shakes.setObjectName("label_shakes")
        self.Layout_shakes.addWidget(self.label_shakes)
        self.spinBox_shakes = QtWidgets.QSpinBox(self.groupBox_scared)
        self.spinBox_shakes.setObjectName("spinBox_shakes")
        self.Layout_shakes.addWidget(self.spinBox_shakes)
        self.verticalLayout_7.addLayout(self.Layout_shakes)
        self.Layout_Beeps = QtWidgets.QHBoxLayout()
        self.Layout_Beeps.setSpacing(6)
        self.Layout_Beeps.setObjectName("Layout_Beeps")
        self.beeps_label = QtWidgets.QLabel(self.groupBox_scared)
        self.beeps_label.setObjectName("beeps_label")
        self.Layout_Beeps.addWidget(self.beeps_label)
        self.beeps_spinBox = QtWidgets.QSpinBox(self.groupBox_scared)
        self.beeps_spinBox.setObjectName("beeps_spinBox")
        self.Layout_Beeps.addWidget(self.beeps_spinBox)
        self.verticalLayout_7.addLayout(self.Layout_Beeps)
        self.gridLayout_7.addWidget(self.groupBox_scared, 0, 2, 1, 1)
        self.groupBox_chirp = QtWidgets.QGroupBox(self.tab_gestures)
        self.groupBox_chirp.setObjectName("groupBox_chirp")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox_chirp)
        self.verticalLayout_8.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_8.setSpacing(6)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.Button_play = QtWidgets.QPushButton(self.groupBox_chirp)
        self.Button_play.setObjectName("Button_play")
        self.verticalLayout_8.addWidget(self.Button_play)
        self.beepsLayout = QtWidgets.QHBoxLayout()
        self.beepsLayout.setSpacing(6)
        self.beepsLayout.setObjectName("beepsLayout")
        self.label_beeps = QtWidgets.QLabel(self.groupBox_chirp)
        self.label_beeps.setObjectName("label_beeps")
        self.beepsLayout.addWidget(self.label_beeps)
        self.spinBox_beeps = QtWidgets.QSpinBox(self.groupBox_chirp)
        self.spinBox_beeps.setObjectName("spinBox_beeps")
        self.beepsLayout.addWidget(self.spinBox_beeps)
        self.verticalLayout_8.addLayout(self.beepsLayout)
        self.gridLayout_7.addWidget(self.groupBox_chirp, 1, 2, 1, 1)
        self.tabs_teleop.addTab(self.tab_gestures, "")
        self.gridLayout_16.addWidget(self.tabs_teleop, 0, 0, 1, 1)
        RosBotMainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(RosBotMainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 517, 26))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuConfiguration = QtWidgets.QMenu(self.menuBar)
        self.menuConfiguration.setObjectName("menuConfiguration")
        RosBotMainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(RosBotMainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        RosBotMainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(RosBotMainWindow)
        self.statusBar.setObjectName("statusBar")
        RosBotMainWindow.setStatusBar(self.statusBar)
        self.action_Contents = QtWidgets.QAction(RosBotMainWindow)
        self.action_Contents.setObjectName("action_Contents")
        self.action_About = QtWidgets.QAction(RosBotMainWindow)
        self.action_About.setObjectName("action_About")
        self.actionExit = QtWidgets.QAction(RosBotMainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionOpen_configuration = QtWidgets.QAction(RosBotMainWindow)
        self.actionOpen_configuration.setEnabled(False)
        self.actionOpen_configuration.setObjectName("actionOpen_configuration")
        self.actionSave_configuration = QtWidgets.QAction(RosBotMainWindow)
        self.actionSave_configuration.setEnabled(False)
        self.actionSave_configuration.setObjectName("actionSave_configuration")
        self.actionServo_configuration = QtWidgets.QAction(RosBotMainWindow)
        self.actionServo_configuration.setObjectName("actionServo_configuration")
        self.actionJoint_configuration = QtWidgets.QAction(RosBotMainWindow)
        self.actionJoint_configuration.setObjectName("actionJoint_configuration")
        self.menuFile.addAction(self.actionOpen_configuration)
        self.menuFile.addAction(self.actionSave_configuration)
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.action_Contents)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.action_About)
        self.menuConfiguration.addAction(self.actionServo_configuration)
        self.menuConfiguration.addAction(self.actionJoint_configuration)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuConfiguration.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())
        self.mainToolBar.addSeparator()

        self.retranslateUi(RosBotMainWindow)
        self.tabs_teleop.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(RosBotMainWindow)

    def retranslateUi(self, RosBotMainWindow):
        _translate = QtCore.QCoreApplication.translate
        RosBotMainWindow.setWindowTitle(_translate("RosBotMainWindow", "RosBotMainWindow"))
        self.groupBox_diag.setTitle(_translate("RosBotMainWindow", "Diagnostic messages"))
        self.textBrowser_log.setPlaceholderText(_translate("RosBotMainWindow", "Robot Teleop GUI Version 0.01"))
        self.groupBox_battery.setTitle(_translate("RosBotMainWindow", "Battery levels:"))
        self.label_pwrRPi.setText(_translate("RosBotMainWindow", "RPi:"))
        self.label_pwrMotor.setText(_translate("RosBotMainWindow", "Power train:"))
        self.groupBox_speed.setTitle(_translate("RosBotMainWindow", "Speed override:"))
        self.label_min.setText(_translate("RosBotMainWindow", "Min"))
        self.label_max.setText(_translate("RosBotMainWindow", "Max"))
        self.groupBox_linear.setTitle(_translate("RosBotMainWindow", "Linear movement:"))
        self.Button_backward.setText(_translate("RosBotMainWindow", "Backward"))
        self.Button_forward.setText(_translate("RosBotMainWindow", "Forward"))
        self.Button_left.setText(_translate("RosBotMainWindow", "Left"))
        self.Button_right.setText(_translate("RosBotMainWindow", "Right"))
        self.groupBox_angular.setTitle(_translate("RosBotMainWindow", "Angular movement:"))
        self.Button_zminus.setText(_translate("RosBotMainWindow", "Rotate Z+"))
        self.Button_zplus.setText(_translate("RosBotMainWindow", "Rotate Z-"))
        self.tabs_teleop.setTabText(self.tabs_teleop.indexOf(self.tab_Movement), _translate("RosBotMainWindow", "Movement"))
        self.groupBox_wave.setTitle(_translate("RosBotMainWindow", "Wave with leg:"))
        self.radioB_fLeft.setText(_translate("RosBotMainWindow", "Front Left"))
        self.radioB_fRight.setText(_translate("RosBotMainWindow", "Front Right"))
        self.radioB_rLeft.setText(_translate("RosBotMainWindow", "Rear Left"))
        self.radioB_rRight.setText(_translate("RosBotMainWindow", "Rear Right"))
        self.Button_wave.setText(_translate("RosBotMainWindow", "Wave"))
        self.groupBox_lean.setTitle(_translate("RosBotMainWindow", "Lean direction:"))
        self.radioB_left.setText(_translate("RosBotMainWindow", "Left"))
        self.radioB_right.setText(_translate("RosBotMainWindow", "Right"))
        self.radioB_forward.setText(_translate("RosBotMainWindow", "Forward"))
        self.radioB_backward.setText(_translate("RosBotMainWindow", "Backward"))
        self.Button_lean.setText(_translate("RosBotMainWindow", "Lean"))
        self.groupBox_scared.setTitle(_translate("RosBotMainWindow", "Scared"))
        self.Button_animate.setText(_translate("RosBotMainWindow", "Animate"))
        self.label_shakes.setText(_translate("RosBotMainWindow", "Shakes:"))
        self.beeps_label.setText(_translate("RosBotMainWindow", "Beeps:"))
        self.groupBox_chirp.setTitle(_translate("RosBotMainWindow", "Chirp"))
        self.Button_play.setText(_translate("RosBotMainWindow", "Play"))
        self.label_beeps.setText(_translate("RosBotMainWindow", "Beeps:"))
        self.tabs_teleop.setTabText(self.tabs_teleop.indexOf(self.tab_gestures), _translate("RosBotMainWindow", "Gestures"))
        self.menuFile.setTitle(_translate("RosBotMainWindow", "File"))
        self.menuHelp.setTitle(_translate("RosBotMainWindow", "Help"))
        self.menuConfiguration.setTitle(_translate("RosBotMainWindow", "Configuration"))
        self.action_Contents.setText(_translate("RosBotMainWindow", "&Contents"))
        self.action_About.setText(_translate("RosBotMainWindow", "&About"))
        self.actionExit.setText(_translate("RosBotMainWindow", "Exit"))
        self.actionOpen_configuration.setText(_translate("RosBotMainWindow", "Open configuration..."))
        self.actionSave_configuration.setText(_translate("RosBotMainWindow", "Save configuration..."))
        self.actionServo_configuration.setText(_translate("RosBotMainWindow", "Servo configuration..."))
        self.actionJoint_configuration.setText(_translate("RosBotMainWindow", "Joint configuration..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RosBotMainWindow = QtWidgets.QMainWindow()
    ui = Ui_RosBotMainWindow()
    ui.setupUi(RosBotMainWindow)
    RosBotMainWindow.show()
    sys.exit(app.exec_())

